### ISSUE TITLE
프론트와 백엔드에서 공통적으로 활용할 API의 정보 상호작용 형식을 정해서 알려주세요

### ISSUE THREAD

**Issue by 10wook** [AnBoIms/Temustargram#4]

**Comment by iveib004** [comment]
https://www.notion.so/AnBoIms-14ab13e467bc80ae9762ec4d0ce4e427

권한 요청하세요

**Comment by iveib004** [comment]
image upload 방식 아직 고민 중에 있습니다
@dltnwjd308 일단 FormData로 전송해주세요

**Comment by iveib004** [comment]
FE -> BE : FormData
BE -> FE : Base64 encoding

**Comment by iveib004** [comment]
file 직접 접근하는
