### ISSUE TITLE
사진에서 선택한 좌표 값을 인풋 받으면,사진을 아웃풋으로 내어주는 코드를 작성해주세요

### ISSUE THREAD

**Issue by 10wook** [AnBoIms/Temustargram#9]

**Comment by iveib004** [comment]
현재 SRNet 연결을 제외한 mmdetection, craft의 API 연결은 완료한 상황입니다
docker-compose로 4개의 이미지 모두 container 안에서 잘 돌아가는 것을 확인했으니, model관련 코드 push해 주세요
모델 코드를 넣고 각 모델별 app.py에 로직을 추가하여 이미지 안에서 돌아가는지 확인해주세요
